### ISSUE TITLE
get tsc frequency problem

### ISSUE THREAD

**Issue by luohaha** [adamsteen/solo5#4]
Hi, I come from here : (http://openbsd-archive.7691.n7.nabble.com/Calculate-the-frequency-of-the-tsc-timecounter-td323570.html)。I have the same issue as you that get tsc frequency on Linux。Have you found out any way to get tsc frequency?

**Comment by adamsteen** [comment]
Hi I am not sure i understand

but see
Linux: https://github.com/adamsteen/solo5/blob/openbsd/ukvm/ukvm_hv_kvm_x86_64.c#L118-L135
FreeBSD: https://github.com/adamsteen/solo5/blob/openbsd/ukvm/ukvm_hv_freebsd_x86_64.c#L126-L138
OpenBSD: https://github.com/adamsteen/solo5/blob/openbsd/ukvm/ukvm_hv_openbsd_x86_64.c#L51-L72

Cheers
Adam
